<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Raketa</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>14</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>283.04825270579886</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>15.760564612929029</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>nosecone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.760564612929029</CalcMass>
                    <CalcCG>68.5360384733841</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>110.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>5</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.0</WallThickness>
                    <ShapeParameter>1.0</ShapeParameter>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>3.324955592153876</KnownMass>
                            <Density>0.0015</Density>
                            <Material>Polyethylene (thin)</Material>
                            <Name>parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>66.0</Xb>
                            <CalcMass>3.324955592153876</CalcMass>
                            <CalcCG>25.500000000000004</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>51.00000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <Dia>400.0</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>600.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>3.0E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Thread (heavy-duty)</ShroudLineMaterial>
                            <DragCoefficient>1.3</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>0.15</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>string</Name>
                            <KnownCG>62.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>62.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>55.0</BaseDia>
                    <ShoulderLen>10.0</ShoulderLen>
                    <ShoulderOD>52.5</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>16.964600329384893</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>container</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>16.964600329384893</CalcMass>
                    <CalcCG>40.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>80.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>55.0</OD>
                    <ID>53.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>53.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>electronics</Name>
                            <KnownCG>14.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>14.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>65.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>5.016005165745623</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>container transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>5.016005165745623</CalcMass>
                    <CalcCG>6.7921265698884845</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>10.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>6</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>10.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>48.0</RearShoulderDia>
                    <FrontDia>55.0</FrontDia>
                    <RearDia>50.0</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>15.550883635269528</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>empty stage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.550883635269528</CalcMass>
                    <CalcCG>80.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>160.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>50.0</OD>
                    <ID>49.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>49.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>7.520187414530552</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>stage joint block</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>7.520187414530552</CalcMass>
                    <CalcCG>7.499999999999993</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>15.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>8</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>10.0</FrontShoulderLen>
                    <RearShoulderLen>10.0</RearShoulderLen>
                    <FrontShoulderDia>48.0</FrontShoulderDia>
                    <RearShoulderDia>48.0</RearShoulderDia>
                    <FrontDia>50.0</FrontDia>
                    <RearDia>50.0</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>15.550883635269528</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>empty stage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.550883635269528</CalcMass>
                    <CalcCG>80.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>160.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>50.0</OD>
                    <ID>49.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>49.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <BodyTube>
                    <KnownMass>15.550883635269528</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PLA</Material>
                    <Name>motor stage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.550883635269528</CalcMass>
                    <CalcCG>80.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>160.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>50.0</OD>
                    <ID>49.0</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>49.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <CustomFinSet>
                            <KnownMass>12.306153614800673</KnownMass>
                            <Density>1250.0</Density>
                            <Material>PLA</Material>
                            <Name>stabilizers</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>12.306153614800673</CalcMass>
                            <CalcCG>89.88222392803362</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>3</FinishCode>
                            <SerialNo>11</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>1.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>140.22117902437847,0.0|133.74288117885592,40.48125|110.19496451218924,40.48125|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>14.294246573833565</KnownMass>
                            <Density>1250.0</Density>
                            <Material>PLA</Material>
                            <Name>Engine block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>14.294246573833565</CalcMass>
                            <CalcCG>35.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>70.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>28.0</OD>
                            <ID>24.0</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.904590546238818</KnownMass>
                            <Density>1250.0</Density>
                            <Material>PLA</Material>
                            <Name>stage joint</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>150.0</Xb>
                            <CalcMass>1.904590546238818</CalcMass>
                            <CalcCG>10.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>20.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>49.0</OD>
                            <ID>48.0</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.5874860377670927</KnownMass>
                            <Density>1250.0</Density>
                            <Material>PLA</Material>
                            <Name>bottom</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1.5874860377670927</CalcMass>
                            <CalcCG>0.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>1.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>49.0</OD>
                            <ID>28.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>